// Generated by CoffeeScript 1.4.0
(function() {
  var decode, request;

  request = require('request');

  decode = require('./decoder').decode;

  request.get({
    url: "http://weather.noaa.gov/pub/data/observations/metar/stations/UIII.TXT"
  }, function(err, resp, body) {
    console.log(body);
    return console.log(decode(body));
  });

}).call(this);
